# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Linters

on:
  pull_request:
      types: [opened, synchronize]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

  linting:
      needs: setup

      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies for testing
        run: |
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: flake8 linting
        run: flake8 .

      - name: isort linting
        run: isort . --check-only

      - name: black linting
        run: black . --check

  testing:
      needs: setup

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies for testing
        run: |
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Test with pytest
        run: python -m pytest
